### ISSUE TITLE
Documentation TODO

### ISSUE THREAD

**Issue by martinfouilleul** [orca-app/orca#35]
- [ ] Update the list of requirements
- [ ] Update the user tooling doc
- [ ] Split and update the dev tooling doc / building instructions to a separate document
- [ ] Update the cheat sheets
- [ ] Comment / write an accompanying tutorial file for each example
- [ ] "Getting Started" files (initially for C, later for other languages)
- [ ] Overview on our core data structures, eg arenas, strings, lists
- [ ] Canvas API documentation. In particular, the affine transform API and the text API might need some more in depth explanations.
- [ ] Setup the infrastructure for a standalone documentation website that we can fill in as we go

**Comment by bvisness** [comment]
Closing this in favor of https://github.com/orca-app/orca-doc/issues/3
