### ISSUE TITLE
Documentation TODO

### ISSUE THREAD

**Issue by bvisness** [orca-app/orca#73]
I have stolen the list of documentation tasks from https://github.com/orca-app/orca/issues/35 to track them here.

- [x] Update the list of requirements
- [ ] Update the user tooling doc
- [x] Split and update the dev tooling doc / building instructions to a separate document
- [ ] Update the cheat sheets
- [ ] Comment / write an accompanying tutorial file for each example
- [x] "Getting Started" files (initially for C, later for other languages)
- [ ] Overview on our core data structures, eg arenas, strings, lists
- [ ] Canvas API documentation. In particular, the affine transform API and the text API might need some more in depth explanations.
- [x] Setup the infrastructure for a standalone documentation website that we can fill in as we go
- [ ] Full API documentation
    - Depends on https://github.com/orca-app/orca/issues/68
- [ ] Convert all function references in the documentation to links to the API spec
